### PR TITLE
Fix readme

### PR DESCRIPTION
**Pull request by GermanBluefox**
Name of argument is wrong: https://github.com/actions-on-google/actionssdk-smart-home-nodejs/blob/master/smart-home-provider/cloud/config-provider.js#L24
It must be "smart-home" and not "smart-home-pub"

### CODE REVIEW

**Comment by Fleker** [comment]
Do you want to include the changes in #55 with this commit?

**Comment by GermanBluefox** [comment]
Yes. I just done it in the browser...

2017-11-05 1:06 GMT+01:00 Nick <notifications@github.com>:

**Comment by Fleker** [comment]
Thanks for the changes. There is another Googler who also sent me a code review with some of these fixes as well as a few more changes. After that change lands I'll take another look at these PRs and see if there's anything that they missed.

**Comment by Fleker** [comment]
Fixed in 413f2c1907e1a8297e4c142c9fea5cce1b1eca80

**Pull request closed without merging**
