### PR TITLE
Couldn't update the settings. Check your connection / login issue getauthcode / login credentials erroneous  /  webcomponents 

### PR DESCRIPTION
**Pull request by orcema**
This happens when you try to link your account with a smartphone but you have no devices defined for your account. With this line of code if no devices are defined for your account,  the return value is an empty object properties

### CODE REVIEW

**Comment by orcema** [comment]
setup CLA

**Comment by orcema** [comment]
the commit 9f8d84b4e9a556b74dbe50f19d4b666dd678f2ef resolves login issue related to non execution of javascript "getauthcode" due to wrong mime type. 
browser caching will be disabled for this script.

**Comment by Fleker** [comment]
I'd like to see a few developers try this out (including myself).

**Comment by Fleker** [comment]
@orcema can you make this two separate PRs? I think the webcomponents change is good, but I would like to get more feedback on the login.

**Pull request closed without merging**
